// src/app/core/services/product.service.ts
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product } from '../../features/product/models/product.dto';

/** Liste mock de produits */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    code: 'PRD001',
    name: 'Casque sans fil',
    description: 'Casque sans fil de haute qualité avec réduction de bruit.',
    image: '',
    category: 'Électronique',
    price: 199.99,
    quantity: 150,
    internalReference: 'CSF-2025-001',
    shellId: 501,
    inventoryStatus: 'INSTOCK',
    rating: 4.7,
    createdAt: new Date('2025-01-10').getTime(),
    updatedAt: new Date('2025-04-05').getTime()
  },
  {
    id: 2,
    code: 'PRD002',
    name: 'Montre connectée',
    description: 'Montre connectée élégante avec multiples fonctionnalités de suivi de santé.',
    image: '',
    category: 'Objets connectés',
    price: 149.99,
    quantity: 80,
    internalReference: 'MC-2025-004',
    shellId: 502,
    inventoryStatus: 'LOWSTOCK',
    rating: 4.3,
    createdAt: new Date('2025-02-15').getTime(),
    updatedAt: new Date('2025-04-20').getTime()
  },
  {
    id: 3,
    code: 'PRD003',
    name: 'Souris gaming',
    description: 'Souris gaming ergonomique avec DPI personnalisable et éclairage RGB.',
    image: '',
    category: 'Accessoires',
    price: 59.99,
    quantity: 0,
    internalReference: 'SG-2025-002',
    shellId: 503,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4.9,
    createdAt: new Date('2025-03-05').getTime(),
    updatedAt: new Date('2025-04-25').getTime()
  },
  {
    id: 4,
    code: 'PRD004',
    name: 'Moniteur 4K',
    description: 'Moniteur Ultra HD 4K avec support HDR et pied réglable.',
    image: '',
    category: 'Électronique',
    price: 329.99,
    quantity: 45,
    internalReference: 'MK-2025-003',
    shellId: 504,
    inventoryStatus: 'INSTOCK',
    rating: 4.5,
    createdAt: new Date('2025-01-20').getTime(),
    updatedAt: new Date('2025-04-10').getTime()
  },
  {
    id: 5,
    code: 'PRD005',
    name: 'Enceinte Bluetooth',
    description: 'Enceinte Bluetooth portable avec basses profondes et longue autonomie.',
    image: '',
    category: 'Audio',
    price: 89.99,
    quantity: 120,
    internalReference: 'EB-2025-005',
    shellId: 505,
    inventoryStatus: 'INSTOCK',
    rating: 4.2,
    createdAt: new Date('2025-02-01').getTime(),
    updatedAt: new Date('2025-04-18').getTime()
  },
  {
    id: 6,
    code: 'PRD006',
    name: 'Clavier mécanique',
    description: 'Clavier mécanique rétroéclairé avec switches Cherry MX.',
    image: '',
    category: 'Accessoires',
    price: 109.99,
    quantity: 75,
    internalReference: 'CM-2025-006',
    shellId: 506,
    inventoryStatus: 'INSTOCK',
    rating: 4.4,
    createdAt: new Date('2025-03-10').getTime(),
    updatedAt: new Date('2025-04-15').getTime()
  },
  {
    id: 7,
    code: 'PRD007',
    name: 'Smartphone',
    description: 'Smartphone dernière génération avec écran OLED et 128 GB de stockage.',
    image: '',
    category: 'Téléphonie',
    price: 799.99,
    quantity: 60,
    internalReference: 'SP-2025-007',
    shellId: 507,
    inventoryStatus: 'INSTOCK',
    rating: 4.6,
    createdAt: new Date('2025-02-20').getTime(),
    updatedAt: new Date('2025-04-22').getTime()
  },
  {
    id: 8,
    code: 'PRD008',
    name: 'Tablette tactile',
    description: 'Tablette tactile 10" avec 64 GB et stylet inclus.',
    image: '',
    category: 'Tablette',
    price: 329.99,
    quantity: 90,
    internalReference: 'TT-2025-008',
    shellId: 508,
    inventoryStatus: 'INSTOCK',
    rating: 4.3,
    createdAt: new Date('2025-03-15').getTime(),
    updatedAt: new Date('2025-04-28').getTime()
  },
  {
    id: 9,
    code: 'PRD009',
    name: 'Appareil photo numérique',
    description: 'Appareil photo compact 20 MP avec zoom optique 10x.',
    image: '',
    category: 'Photo',
    price: 249.99,
    quantity: 30,
    internalReference: 'AP-2025-009',
    shellId: 509,
    inventoryStatus: 'LOWSTOCK',
    rating: 4.5,
    createdAt: new Date('2025-01-25').getTime(),
    updatedAt: new Date('2025-04-12').getTime()
  },
  {
    id: 10,
    code: 'PRD010',
    name: 'Casque de réalité virtuelle',
    description: 'Casque VR immersif avec manettes sans fil.',
    image: '',
    category: 'Électronique',
    price: 299.99,
    quantity: 40,
    internalReference: 'VR-2025-010',
    shellId: 510,
    inventoryStatus: 'INSTOCK',
    rating: 4.4,
    createdAt: new Date('2025-02-05').getTime(),
    updatedAt: new Date('2025-04-30').getTime()
  },
  {
    id: 11,
    code: 'PRD011',
    name: 'Chargeur sans fil',
    description: 'Chargeur à induction rapide compatible Qi.',
    image: '',
    category: 'Accessoires',
    price: 29.99,
    quantity: 200,
    internalReference: 'CSF-2025-011',
    shellId: 511,
    inventoryStatus: 'INSTOCK',
    rating: 4.1,
    createdAt: new Date('2025-01-30').getTime(),
    updatedAt: new Date('2025-04-16').getTime()
  },
  {
    id: 12,
    code: 'PRD012',
    name: 'Disque dur externe',
    description: 'Disque dur portable 2 TB USB 3.0.',
    image: '',
    category: 'Stockage',
    price: 79.99,
    quantity: 110,
    internalReference: 'DE-2025-012',
    shellId: 512,
    inventoryStatus: 'INSTOCK',
    rating: 4.2,
    createdAt: new Date('2025-03-22').getTime(),
    updatedAt: new Date('2025-04-27').getTime()
  },
  {
    id: 13,
    code: 'PRD013',
    name: 'Routeur Wi-Fi',
    description: 'Routeur Wi-Fi dual-band 802.11ac.',
    image: '',
    category: 'Réseau',
    price: 119.99,
    quantity: 55,
    internalReference: 'RW-2025-013',
    shellId: 513,
    inventoryStatus: 'INSTOCK',
    rating: 4.0,
    createdAt: new Date('2025-02-28').getTime(),
    updatedAt: new Date('2025-04-14').getTime()
  },
  {
    id: 14,
    code: 'PRD014',
    name: 'Imprimante laser',
    description: 'Imprimante laser monochrome avec scanner intégré.',
    image: '',
    category: 'Bureau',
    price: 159.99,
    quantity: 25,
    internalReference: 'IL-2025-014',
    shellId: 514,
    inventoryStatus: 'LOWSTOCK',
    rating: 4.3,
    createdAt: new Date('2025-01-15').getTime(),
    updatedAt: new Date('2025-04-09').getTime()
  },
  {
    id: 15,
    code: 'PRD015',
    name: 'Clé USB',
    description: 'Clé USB 32 GB haute vitesse.',
    image: '',
    category: 'Stockage',
    price: 12.99,
    quantity: 300,
    internalReference: 'CU-2025-015',
    shellId: 515,
    inventoryStatus: 'INSTOCK',
    rating: 4.1,
    createdAt: new Date('2025-02-10').getTime(),
    updatedAt: new Date('2025-04-17').getTime()
  },
  {
    id: 16,
    code: 'PRD016',
    name: 'Projecteur portable',
    description: 'Projecteur LED portable Full HD.',
    image: '',
    category: 'Audio/Vidéo',
    price: 249.99,
    quantity: 35,
    internalReference: 'PP-2025-016',
    shellId: 516,
    inventoryStatus: 'INSTOCK',
    rating: 4.4,
    createdAt: new Date('2025-03-01').getTime(),
    updatedAt: new Date('2025-04-23').getTime()
  },
  {
    id: 17,
    code: 'PRD017',
    name: 'Webcam HD',
    description: 'Webcam Full HD 1080p avec microphone intégré.',
    image: '',
    category: 'Accessoires',
    price: 49.99,
    quantity: 85,
    internalReference: 'WC-2025-017',
    shellId: 517,
    inventoryStatus: 'INSTOCK',
    rating: 4.2,
    createdAt: new Date('2025-02-25').getTime(),
    updatedAt: new Date('2025-04-19').getTime()
  },
  {
    id: 18,
    code: 'PRD018',
    name: 'Barre de son',
    description: 'Barre de son 2.1 avec subwoofer sans fil.',
    image: '',
    category: 'Audio',
    price: 179.99,
    quantity: 70,
    internalReference: 'BS-2025-018',
    shellId: 518,
    inventoryStatus: 'INSTOCK',
    rating: 4.5,
    createdAt: new Date('2025-03-12').getTime(),
    updatedAt: new Date('2025-04-29').getTime()
  },
  {
    id: 19,
    code: 'PRD019',
    name: 'Tapis de souris gaming',
    description: 'Tapis de souris gaming XL antidérapant.',
    image: '',
    category: 'Accessoires',
    price: 19.99,
    quantity: 250,
    internalReference: 'TG-2025-019',
    shellId: 519,
    inventoryStatus: 'INSTOCK',
    rating: 4.3,
    createdAt: new Date('2025-01-30').getTime(),
    updatedAt: new Date('2025-04-16').getTime()
  },
  {
    id: 20,
    code: 'PRD020',
    name: 'Lampe LED intelligente',
    description: 'Lampe LED connectée RGB contrôlable via application mobile.',
    image: '',
    category: 'Maison connectée',
    price: 39.99,
    quantity: 140,
    internalReference: 'LL-2025-020',
    shellId: 520,
    inventoryStatus: 'INSTOCK',
    rating: 4.0,
    createdAt: new Date('2025-02-18').getTime(),
    updatedAt: new Date('2025-04-21').getTime()
  }
];


@Injectable({
  providedIn: 'root'
})
export class ProductService {
  /** Récupère tous les produits */
  getAll(): Observable<Product[]> {
    return of(MOCK_PRODUCTS);
  }

  /** Récupère un produit par son id */
  getById(id: number): Observable<Product | undefined> {
    const product = MOCK_PRODUCTS.find(p => p.id === id);
    return of(product);
  }
}
